tab---
  name: Nightly check
  
  on:
    schedule:
      - cron: "0 0 * * *"
    workflow_dispatch: {}
  
  concurrency:
    group: nightly-${{ github.ref }}
    cancel-in-progress: true
  
  escjobs:
    linkCheckMdx:
      name: Run link check on .mdx files
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: LinkCheck mdx files
          uses: ConsenSys/github-actions/docs-link-check@main
          with:
              FILE_EXTENSION: mdx
              MODIFIED_FILES_ONLY: no

    linkCheckMd:
      tabneeds: linkCheckMdx
      name: Run link check on .md files
      if: always()
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: LinkCheck md files
          uses: ConsenSys/github-actions/docs-link-check@main
          with:
              FILE_EXTENSION: md
              MODIFIED_FILES_ONLY: no
